CREATE TABLE IF NOT EXISTS UserRoles (
    UserRolesId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    RoleName TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Users (
    UsersId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    UsernameOrEmail TEXT NOT NULL UNIQUE,
    UserRolesId INTEGER NOT NULL,
    FOREIGN KEY (UserRolesId) REFERENCES UserRoles(UserRolesId)
);

CREATE TABLE IF NOT EXISTS UserCredentials (
    UserCredentialsId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    UsersId INTEGER NOT NULL UNIQUE,
    HashedPassword TEXT NOT NULL,
    FOREIGN KEY (UsersId) REFERENCES Users(UsersId)
);

CREATE TABLE IF NOT EXISTS UserContactDetails (
    UserContactDetailsId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    FullName TEXT NOT NULL,
    UsersId INTEGER NOT NULL UNIQUE,
    Telephone TEXT,
    FOREIGN KEY (UsersId) REFERENCES Users(UsersId)
);

CREATE TABLE IF NOT EXISTS Tours (
    ToursId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TourStartDate DATE NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RoomTypes (
    RoomTypesId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    RoomName TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RoomCostInfo (
    RoomCostInfoId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    RoomTypesId INTEGER UNIQUE NOT NULL,
    DefaultQuantity INTEGER NOT NULL,
    CurrentPricePence INTEGER NOT NULL,
    DiscountRate INTEGER NOT NULL,
    FOREIGN KEY (RoomTypesId) REFERENCES RoomTypes(RoomTypesId)
);

CREATE TABLE IF NOT EXISTS RoomTypesTours (
    RoomTypesToursId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ToursId INTEGER NOT NULL,
    RoomTypesId INTEGER NOT NULL,
    CurrentQuantity INTEGER NOT NULL,
    FOREIGN KEY (ToursId) REFERENCES Tours(ToursId),
    FOREIGN KEY (RoomTypesId) REFERENCES RoomTypes(RoomTypesId),
    UNIQUE (ToursId, RoomTypesId)
);

CREATE TABLE IF NOT EXISTS BookingStates (
    BookingStatesId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    BookingState TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Bookings (
    BookingsId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    UsersId INTEGER NOT NULL,
    ToursId INTEGER NOT NULL,
    RoomTypesId INTEGER NOT NULL,
    BookingStatesId INTEGER NOT NULL,
    BookingPrice INTEGER NOT NULL,
    FOREIGN KEY (UsersId) REFERENCES Users(UsersId),
    FOREIGN KEY (ToursId) REFERENCES Tours(ToursId),
    FOREIGN KEY (RoomTypesId) REFERENCES RoomTypes(RoomTypesId),
    FOREIGN KEY (BookingStatesId) REFERENCES BookingStates(BookingStatesId)
);